
name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-11-jdk \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-dev \
            unzip \
            zlib1g-dev \
            libsqlite3-dev \
            git

      - name: Install Cython and Buildozer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install cython==0.29.28
          python3 -m pip install buildozer

      - name: Initialize Buildozer
        run: buildozer init

      - name: Configure buildozer.spec
        run: |
          sed -i 's/^requirements = .*/requirements = python3,kivy/' buildozer.spec
          sed -i 's/^title = .*/title = Glitch Strength Simulator/' buildozer.spec
          sed -i 's/^package.name = .*/package.name = glitchstrength/' buildozer.spec
          sed -i 's/^package.domain = .*/package.domain = org.example/' buildozer.spec

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: GlitchStrengthSimulator-debug.apk
          path: bin/*.apk
