
name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk build-essential libssl-dev libffi-dev python3-dev unzip zlib1g-dev libsqlite3-dev git

      - name: Install Buildozer
        run: |
          pip install cython==0.29.36
          pip install buildozer

      - name: Init Buildozer
        run: buildozer init

      - name: Configure buildozer.spec
        run: |
          sed -i 's/^requirements = .*/requirements = python3,kivy/' buildozer.spec
          sed -i 's/^title = .*/title = Glitch Strength Simulator/' buildozer.spec

      - name: Copy your code into the build directory
        run: cp main.py ./

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: GlitchStrengthSimulator.apk
          path: bin/*.apk
          
